name: Stop Railway API

on:
  schedule:
    - cron: "0 12 * * 1-5" # 9h Brasília (UTC+3)
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Railway service
        run: |
          curl -X POST https://backboard.railway.app/graphql \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query":"mutation { pauseService(input: { serviceId: \"${{ secrets.SERVICE_ID }}\" }) { id } }"}'
